apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-28T06:26:41Z"
  labels:
    qcloud-app: athena-web
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:qcloud-app: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":4010,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":5000,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":8070,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":8123,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:qcloud-app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl
      operation: Update
      time: "2020-09-28T06:26:41Z"
  name: athena-web
  namespace: prod
  resourceVersion: "32941274"
  selfLink: /api/v1/namespaces/prod/services/athena-web
  uid: acf04261-d414-4000-b8a4-9481963556ae
spec:
  clusterIP: 172.16.255.20
  externalTrafficPolicy: Cluster
  ports:
    - name: tcp-8070-8070
      nodePort: 30886
      port: 8070
      protocol: TCP
      targetPort: 8070
    - name: tcp-5000-5000
      nodePort: 31695
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: tcp-8123-8123
      nodePort: 31323
      port: 8123
      protocol: TCP
      targetPort: 8123
    - name: tcp-4010-4010
      nodePort: 32378
      port: 4010
      protocol: TCP
      targetPort: 4010
  selector:
    qcloud-app: athena-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
